server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: Sruthi@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE

# Security settings
security:
  user:
    name: user
    password: password

# CORS configuration
cors:
  allowed-origins: "*"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"